aman-raza/Friends_Hack

calculator/calculator.py

simple calculator in pyhton

---

bootstrap tests/bootstrap.py

Hi ! I'm still a beginner in the github game, here's my first pull request in context of Hacktober.
This is a function that allows you to run a bootstrap test easily and returns a p-value depending on the tested mean.
I'll work more on this folder to add other resampling tests in the future.

Create a Bootstrap test

---

Magic8Ball.py

A very simple and fun game to answer questions for fun

Magic8Ball

---

Phyllotaxis.py

Install pygame using 'pip install pygame'

Added Phyllotaxis.py

---

fibonacci_recursion.c

Added Fibonacci series code in C

add fibonacci series code in C

---

URL-Shortener/README.md
URL-Shortener/UrlShortner.py

I have added the basic code for URL shortener

Basic Code of Url Shortener

---

c++ tree and knapsack/Treelevel_order_sum.cpp
c++ tree and knapsack/fractional_knapsack.cpp

Added c++ codes demonstrating maximum level order sum in a tree and fractional knapsack.

Tree and Knapsack

---

Download_Speed_Tracker.py
Game_Of_Life/app.py.py
Game_Of_Life/array_functions.py
Game_Of_Life/life.py
Graph_Algorithms_Python/BFS.py
Graph_Algorithms_Python/DFS.py
Graph_Algorithms_Python/tree.py
Graph_Algorithms_Python/tree_height.py
Infix2Postfix.cpp
README.md

Added 2 files
* Updated README.md
* Infix2Postfix.cpp - To convert Infix to postfix statement

README.md updated | Infix2Postfix in C++

---

Download_Speed_Tracker.py
Game_Of_Life/app.py.py
Game_Of_Life/array_functions.py
Game_Of_Life/life.py
Graph_Algorithms_Python/BFS.py
Graph_Algorithms_Python/DFS.py
Graph_Algorithms_Python/tree.py
Graph_Algorithms_Python/tree_height.py

Added 3 files/folders
* Conway's Game of Life(Game_Of_Life) - A simulation game in python
* Download_Speed_Tracker - A simple app to track network speeds in Python
* Some Graph Theoretic Algorithms Like DFS, BFS, tree, tree height along with detailed explanation.

Added 3 folders/files

---

simple_cla.html

Hey there,
I have added a simple working calculator.

Simple working calculator

---

Bubble_sort.py

New to git. Please check if it's alright.

Added bubble_sort.py

---

partition_soverniers.py

Adding Discrete Knapsack Problem.

---

CPP/Tower Of Hanoi.cpp

Create Tower Of Hanoi #19

---

Floyd's Triangle.py

Added Floyd's Triangle code using python.

Add Floyd's Triangle code

---

String/Making_Anagrams.py

Minimum deletions required to make 2 strings anagrams

Making Anagrams from given strings

---

BFS & its application/0-1bfs.py
BFS & its application/bfs.py
BFS & its application/find_all_the_edges_on_shortest_path_btw_2_vertices.py
BFS & its application/find_all_the_vertices_on_shortest_path_btw_2_vertices.py
BFS & its application/find_connected_nodes_using_bfs.py
BFS & its application/find_shortest_path_of_even_len.py
BFS & its application/shorest-cycle-in-undirected-graph.py

I have added some python codes to demonstrate bfs and its application in graphs

BFS and its Application

---

guess.py

add guess game

---

CPP/bst.c

added bst program

---

ALPHABET.C
COMPOUND.C
NSTRONG.C

adding Basic C programs for other fellow coders

Added Basic C program

---

longestCommonSubsequence.py

I want to upload this program in your repo

longestCommonSubsequence

---

CPP/Johnson’s Algorithm/README.md
CPP/Johnson’s Algorithm/johnson.cpp
CPP/Minimum Spanning Tree Algorithm/Kruskal/README.md
CPP/Minimum Spanning Tree Algorithm/Kruskal/code.cpp
CPP/Minimum Spanning Tree Algorithm/README.md

Created CPP / Johnson’s algorithm & CPP / Minimum Spanning Tree folders ( with code.cpp + beautiful readme.md ) !!! 
Added folders & files:-
CPP / Johnson's Algorithm
----- CPP / Johnson's Algorithm / johnson.cpp
----- CPP / Johnson's Algorithm / README.md
CPP / Minimum Spanning Tree Algorithm
----- CPP / Minimum Spanning Tree Algorithm / README.md
---------- CPP / Minimum Spanning Tree Algorithm / Krushal / code.cpp
---------- CPP / Minimum Spanning Tree Algorithm / Krushal / README.md

Added Johnson’s algorithm & Minimum Spanning Tree in CPP folder ( with code.cpp + beautiful readme.md ) !!! (click me & see comment for more info)

---

Bubble_sort.py

Bubble_sort.py fix IndentationError

---

Python projects/Merge Multiple PDF/source-code.py

Remove Python syntax error from merge multiple PDFs

---

Car Racing/RaceGame.py

Like https://github.com/lordmauve/pgzero/blob/master/.flake8
#122 + #123 + #124 + #125 should turn our GitHub Actions tests green.

pgzrun magically defines Actor, keyboard, screen

---

gui calc.py

GUI Calculator

---

diameterBinaryTree.cpp

Diameter of a Binary Tree

---

2ndoct_zigzag_yash2001340.cpp

I created zigzag showing numbers code please accept my merge and add it in your repository

Create zigzag numbers using c++ 2ndoct_zigzag_yash2001340.cpp

---

Ball-Fall-Game/app.js
Ball-Fall-Game/index.html
Ball-Fall-Game/readme.md
Ball-Fall-Game/style.css
CONTRIBUTING.md

new pull request with appropriate files changed.

Ball-Fall-Game added

---

CPP/Check if two arrays are equal or not.cpp

Program Check if two arrays are equal or not in c++.

Check if two arrays are equal or not.cpp

---

Circular_Queue.cpp

C++ program for insertion and deletion in Circular Queue

Circular_Queue.cpp
